### ISSUE TITLE
Twitter not picking up featured image on current theme

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-theme-summit#18]
Kat Drew reports:

> Yesterday I was trying to tweet and Twitter wouldn't post my feature image. I did some digging and I think it's because our wordpress site is out of date? Do you have any insights on this?
>
> Not urgent at all but just wanted to flag it - it would be nice to be able to include the images as we get closer to Summit as it looks nicer. 

## Task

- [ ] ensure social media previews work on the *new* CreativeCommons.org theme
    - [ ] Twitter
    - [ ] Facebook
    - [ ] Instagram?

**Comment by alainseys** [comment]
@brylie  can you post te steps so i can reproduce this ? the default post uses https://twitter.com/intent/tweet?via=creativecommons&text=this-is-my-test.

alternative you could enable auto update of the wp core in 'wp-config.php' 

```
define( 'WP_AUTO_UPDATE_CORE', true );
```

**Comment by brylie** [comment]
> an you post te steps so i can reproduce this ?

I am not able to reproduce the issue either:

![Peek 2021-09-20 13-07](https://user-images.githubusercontent.com/17307/133985931-095d9f63-77c6-43d4-8487-015de2fec819.gif)

> alternative you could enable auto update of the wp core in 'wp-config.php'

We are hesitant to enable core updates, but can revisit the suggestion at our next weekly planning meeting.

**Comment by brylie** [comment]
My mistake. Kat Drew is working on the Summit website promotion. Here are the steps to reproduce.

1. visit https://summit.creativecommons.org
2. view any page, such as the [Access Fund](https://summit.creativecommons.org/summit-access-fund/) page
3. copy page URL
4. go to Twitter
5. paste the URL into the new tweet box
6. notice there is no page preview or featured image

**Comment by brylie** [comment]
For what it's worth, the Summit website isn't lagging too far behind the latest WordPress version

![image](https://user-images.githubusercontent.com/17307/133987166-0dc56237-6370-4a79-b7ab-b537d38ab644.png)


> WordPress 5.5 “Eckstine” was released to the public on August 11, 2020.

https://wordpress.org/support/wordpress-version/version-5-5/

**Comment by possumbilities** [comment]
Closing, as this site is no longe Live, and the associated theme is being archived.
